site_name: JARVICE
theme: readthedocs
extra_css:
    - css/extra.css
pages:
    - Home: index.md
    - CI/CD Pipeline: cicd.md
    - Docker Images on JARVICE: docker.md
    - Public Applications: public.md

